name: docker_push

on:
  workflow_dispatch:

jobs:
  fetch_version:
    runs-on: ubuntu-latest
    outputs:
      push_tag: ${{ steps.fetch_version.outputs.push_tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch Caddy Version
        id: fetch_version
        run:  python3 ./fetch_tags_need_push.py >> $GITHUB_OUTPUT
  docker_push:
    runs-on: ubuntu-latest
    if: jobs.fetch_version.outputs.fetch_version != ''
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate Dockerfile
        run: ./gen_docker_file.sh ${{ jobs.fetch_version.outputs.fetch_version }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6, linux/arm/v7, linux/arm64, linux/ppc64le
          push: true
          tags: leoppro/docker-caddy-webdav:latest, leoppro/docker-caddy-webdav:${{ jobs.fetch_version.outputs.fetch_version }} 
