name: docker_push

on:
  workflow_dispatch:
    inputs:
      tag:
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      - 
        name: Install gomplate
        run: sudo apt-get update && sudo apt-get install -y gomplate
      -
        name: Generate Dockerfile
        run: ./gen_docker_file.sh ${{ inputs.tag }}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm/v6, linux/arm/v7, linux/arm64, linux/ppc64le, linux/s390x
          push: false
          tags: leoppro/docker-caddy-webdav:latest, leoppro/docker-caddy-webdav:${{ inputs.tag }} 
